<#
.SYNOPSIS
    O2 System - Full setup for a new cashier station (works fully offline).

.DESCRIPTION
    Called by installer/setup.iss (Inno Setup) after it extracts all bundled
    files. PHP, Node, Chrome, NSSM, and a full vendored copy of the project
    must already exist locally - this script only wires them together. It
    never downloads anything from the internet.

    Steps:
      1. Enable required PHP extensions (intl, pdo_mysql, ...) in php.ini.
      2. Write .env with the central DB connection + bundled Chrome path.
      3. Register 3 Windows services via NSSM (queue worker, print bridge,
         render server) so they auto-start on boot and auto-restart on crash.

.NOTES
    Run PowerShell as Administrator (NSSM needs admin rights to register
    services).
#>

param(
    [Parameter(Mandatory = $true)] [string]$InstallDir,
    [Parameter(Mandatory = $true)] [string]$PhpDir,
    [Parameter(Mandatory = $true)] [string]$NodeDir,
    [Parameter(Mandatory = $true)] [string]$ChromeExe,
    [Parameter(Mandatory = $true)] [string]$NssmExe,

    [string]$DbHost     = "192.168.2.250",
    [string]$DbPort     = "3306",
    [string]$DbDatabase = "o2system",
    [string]$DbUsername = "admin",
    [Parameter(Mandatory = $true)] [string]$DbPassword,

    [string]$PrinterName = "XP-80C",
    [string]$AppKey      = "",  # empty = will be generated automatically

    # The services must run as a real logged-in Windows user (not the
    # default LocalSystem), because Browsershot/Puppeteer need to launch a
    # real browser process (Chrome/Edge) and that reliably fails under
    # LocalSystem due to Windows session/desktop restrictions. Pass the
    # Windows account that's normally logged into this cashier machine.
    # Leave both empty to keep the NSSM default (LocalSystem) - only do
    # that if you already know browser launching works fine under it.
    [string]$ServiceUsername = "",
    [string]$ServicePassword = "",

    # One-time activation code for this station's PosRegister (generated by
    # an admin in the back office, valid 15 minutes - see
    # PosRegisterController::generateActivationToken()). Activating binds
    # this specific device to one PosRegister row and gives back its ID,
    # which we then use to scope this station's queue worker to ONLY the
    # print jobs meant for it (see OrderPrintingService::resolveQueueForOrder()).
    # Leave empty to skip activation - the queue worker then falls back to
    # the shared "default" queue, same as before this feature existed.
    [string]$ActivationToken = "",
    [string]$AppUrl = "http://192.168.2.250:8095"
)

$ErrorActionPreference = "Stop"

function Write-Step($msg)  { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)    { Write-Host "    OK: $msg" -ForegroundColor Green }
function Write-Warn2($msg) { Write-Host "    WARNING: $msg" -ForegroundColor Yellow }

$phpExe = Join-Path $PhpDir "php.exe"
$nodeExe = Join-Path $NodeDir "node.exe"

# Queue name(s) the O2QueueWorker service will listen on. Overwritten below
# if station activation succeeds; stays "default" otherwise (old behavior).
$script:posRegisterQueueName = "default"

if (-not (Test-Path $phpExe))    { throw "php.exe not found in $PhpDir" }
if (-not (Test-Path $nodeExe))   { throw "node.exe not found in $NodeDir" }
if (-not (Test-Path $ChromeExe)) { throw "chrome.exe not found at $ChromeExe" }
if (-not (Test-Path $NssmExe))   { throw "nssm.exe not found at $NssmExe" }
if (-not (Test-Path $InstallDir)) { throw "Project folder not found at $InstallDir" }

# -- 1) php.ini: enable required extensions ------------------------------
Write-Step "Preparing php.ini..."

$phpIni = Join-Path $PhpDir "php.ini"
if (-not (Test-Path $phpIni)) {
    $prod = Join-Path $PhpDir "php.ini-production"
    if (Test-Path $prod) {
        Copy-Item $prod $phpIni
    } else {
        throw "Neither php.ini nor php.ini-production found in $PhpDir"
    }
}

$requiredExtensions = @("intl", "pdo_mysql", "mbstring", "fileinfo", "curl", "gd", "openssl", "zip")
$iniLines = Get-Content $phpIni
for ($i = 0; $i -lt $iniLines.Count; $i++) {
    foreach ($ext in $requiredExtensions) {
        if ($iniLines[$i] -match "^\s*;\s*extension\s*=\s*$ext\s*$") {
            $iniLines[$i] = "extension=$ext"
        }
    }
    if ($iniLines[$i] -match "^\s*;?\s*extension_dir\s*=") {
        $iniLines[$i] = 'extension_dir = "ext"'
    }
}
Set-Content -Path $phpIni -Value $iniLines -Encoding UTF8

# Make sure every extension actually ended up enabled (append if missing entirely)
$iniContent = Get-Content $phpIni -Raw
foreach ($ext in $requiredExtensions) {
    if ($iniContent -notmatch "(?m)^extension=$ext\s*$") {
        Add-Content -Path $phpIni -Value "extension=$ext"
    }
}

Write-Ok "php.ini ready (intl, pdo_mysql, mbstring, fileinfo, curl, gd, openssl, zip)"

# Verify PHP actually loads them
$prevEap0 = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$loadedExtensions = (& $phpExe -m 2>&1) | ForEach-Object { $_.Trim().ToLower() }
$ErrorActionPreference = $prevEap0
foreach ($ext in $requiredExtensions) {
    if ($loadedExtensions -notcontains $ext.ToLower()) {
        Write-Warn2 "Extension '$ext' did not show up in 'php -m' - check manually if printing breaks."
    }
}

# -- 2) Add PHP and Node to PATH (machine-wide) ---------------------------
Write-Step "Adding PHP and Node to PATH..."

$machinePath = [Environment]::GetEnvironmentVariable("Path", "Machine")
$pathsToAdd = @($PhpDir, $NodeDir)
$changed = $false
foreach ($p in $pathsToAdd) {
    if ($machinePath -notlike "*$p*") {
        $machinePath = "$machinePath;$p"
        $changed = $true
    }
}
if ($changed) {
    [Environment]::SetEnvironmentVariable("Path", $machinePath, "Machine")
    $env:Path = "$env:Path;$PhpDir;$NodeDir"
}
Write-Ok "PATH updated"

# -- 3) .env ------------------------------------------------------------
Write-Step "Preparing .env..."

Push-Location $InstallDir
try {
    $envPath = Join-Path $InstallDir ".env"
    if (-not (Test-Path $envPath)) {
        $examplePath = Join-Path $InstallDir ".env.example"
        if (Test-Path $examplePath) {
            Copy-Item $examplePath $envPath
        } else {
            New-Item -ItemType File -Path $envPath | Out-Null
        }
    }

    function Set-EnvValue([string]$Path, [string]$Key, [string]$Value) {
        # Always double-quote the value (dotenv-safe) so spaces, #, $, and
        # other special characters in things like DB_PASSWORD never break
        # parsing. Escape any literal double quotes/backslashes inside it.
        $escaped = $Value -replace '\\', '\\\\' -replace '"', '\"'
        $quoted = '"' + $escaped + '"'

        $lines = Get-Content $Path
        $pattern = "^#?\s*$Key\s*="
        $found = $false
        for ($i = 0; $i -lt $lines.Count; $i++) {
            if ($lines[$i] -match $pattern) {
                $lines[$i] = "$Key=$quoted"
                $found = $true
                break
            }
        }
        if (-not $found) {
            $lines += "$Key=$quoted"
        }
        Set-Content -Path $Path -Value $lines -Encoding UTF8
    }

    # Forward slashes so the path never needs escaping inside .env
    $chromePathForEnv = $ChromeExe -replace '\\', '/'

    Set-EnvValue $envPath "APP_ENV" "production"
    Set-EnvValue $envPath "APP_DEBUG" "false"
    Set-EnvValue $envPath "DB_CONNECTION" "mysql"
    Set-EnvValue $envPath "DB_HOST" $DbHost
    Set-EnvValue $envPath "DB_PORT" $DbPort
    Set-EnvValue $envPath "DB_DATABASE" $DbDatabase
    Set-EnvValue $envPath "DB_USERNAME" $DbUsername
    Set-EnvValue $envPath "DB_PASSWORD" $DbPassword
    Set-EnvValue $envPath "QUEUE_CONNECTION" "database"
    Set-EnvValue $envPath "BROWSERSHOT_CHROME_PATH" $chromePathForEnv
    Set-EnvValue $envPath "RENDER_SERVER_ENABLED" "true"
    Set-EnvValue $envPath "RENDER_SERVER_URL" "http://127.0.0.1:4790/render"

    Write-Ok ".env ready"

    if ($AppKey -ne "") {
        Set-EnvValue $envPath "APP_KEY" $AppKey
        Write-Ok "APP_KEY set from provided value"
    } else {
        $hasKey = (Get-Content $envPath -Raw) -match "(?m)^APP_KEY=base64:"
        if (-not $hasKey) {
            $prevEap1 = $ErrorActionPreference
            $ErrorActionPreference = "Continue"
            & $phpExe artisan key:generate --force 2>&1 | Out-Null
            $ErrorActionPreference = $prevEap1
            Write-Ok "APP_KEY generated"
        }
    }

    # Clear any stale cached config from a previous install. Any warning
    # artisan writes to stderr here is non-fatal, so don't let it abort
    # the whole script.
    $prevEap2 = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    & $phpExe artisan config:clear 2>&1 | Out-Null
    $ErrorActionPreference = $prevEap2

    # -- Activate this station's PosRegister (optional) ------------------
    # Binds this specific device to one PosRegister row in the central DB
    # and gets back its ID, which scopes this station's queue worker so it
    # ONLY picks up print jobs meant for it - never another station's.
    # See OrderPrintingService::resolveQueueForOrder() for the other half.
    if ($ActivationToken -ne "") {
        Write-Step "Activating this station (PosRegister)..."
        try {
            $activateUrl = "$AppUrl/api/pos/activate"
            $body = @{ token = $ActivationToken } | ConvertTo-Json
            $response = Invoke-RestMethod -Uri $activateUrl -Method Post -Body $body -ContentType "application/json" -TimeoutSec 15

            if ($response.success) {
                $posRegisterId = $response.pos_info.id
                $posRegisterCode = $response.pos_info.code
                Set-EnvValue $envPath "POS_REGISTER_ID" $posRegisterId
                Set-EnvValue $envPath "POS_REGISTER_CODE" $posRegisterCode
                $script:posRegisterQueueName = "pos-register-$posRegisterId,default"
                Write-Ok "Station activated as $posRegisterCode (id=$posRegisterId)"
            } else {
                Write-Warn2 "Activation failed: $($response.message)"
                Write-Warn2 "Queue worker will use the shared 'default' queue - printing still works, just without station isolation."
            }
        } catch {
            Write-Warn2 "Could not reach activation endpoint (${activateUrl}): $($_.Exception.Message)"
            Write-Warn2 "Queue worker will use the shared 'default' queue - printing still works, just without station isolation."
        }
    } else {
        Write-Warn2 "No -ActivationToken given - queue worker will use the shared 'default' queue (no station isolation)."
    }
}
finally {
    Pop-Location
}

# -- 4) Register services via NSSM ----------------------------------------
Write-Step "Registering Windows services..."

function Install-O2Service {
    param(
        [string]$Name,
        [string]$Exe,
        [string]$Arguments,
        [string]$Description
    )

    $logDir = Join-Path $InstallDir "storage\logs"
    if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }

    # nssm.exe writes plain status text to stderr for things like "service
    # doesn't exist yet" (expected on a first install) - with
    # $ErrorActionPreference = "Stop" that gets treated as a terminating
    # error otherwise. Relax it for this whole native-command sequence and
    # check exit codes explicitly for the two calls that actually matter.
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        & $NssmExe stop $Name 2>&1 | Out-Null
        & $NssmExe remove $Name confirm 2>&1 | Out-Null

        & $NssmExe install $Name $Exe $Arguments 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) {
            throw "nssm install failed for $Name (exit code $LASTEXITCODE)"
        }

        & $NssmExe set $Name AppDirectory $InstallDir 2>&1 | Out-Null
        & $NssmExe set $Name DisplayName "O2 - $Name" 2>&1 | Out-Null
        & $NssmExe set $Name Description $Description 2>&1 | Out-Null
        & $NssmExe set $Name AppStdout (Join-Path $logDir "$Name.out.log") 2>&1 | Out-Null
        & $NssmExe set $Name AppStderr (Join-Path $logDir "$Name.err.log") 2>&1 | Out-Null
        & $NssmExe set $Name AppRotateFiles 1 2>&1 | Out-Null
        & $NssmExe set $Name AppRotateBytes 5242880 2>&1 | Out-Null
        & $NssmExe set $Name Start SERVICE_AUTO_START 2>&1 | Out-Null
        & $NssmExe set $Name AppExit Default Restart 2>&1 | Out-Null
        & $NssmExe set $Name AppRestartDelay 3000 2>&1 | Out-Null

        if ($ServiceUsername -ne "") {
            $qualifiedUser = if ($ServiceUsername -like "*\*") { $ServiceUsername } else { ".\$ServiceUsername" }
            & $NssmExe set $Name ObjectName $qualifiedUser $ServicePassword 2>&1 | Out-Null
            if ($LASTEXITCODE -ne 0) {
                throw "nssm set ObjectName failed for $Name (exit code $LASTEXITCODE) - check the Windows username/password"
            }
        }

        & $NssmExe start $Name 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0 -and $LASTEXITCODE -ne 2) {
            # exit code 2 = SERVICE_ALREADY_RUNNING, harmless
            throw "nssm start failed for $Name (exit code $LASTEXITCODE)"
        }
    }
    finally {
        $ErrorActionPreference = $prevEap
    }

    Write-Ok "Service $Name registered and started"
}

Install-O2Service `
    -Name "O2PrintBridge" `
    -Exe $phpExe `
    -Arguments "print-bridge.php --printer=`"$PrinterName`" --listen=127.0.0.1:9100" `
    -Description "O2 System - local USB printer bridge"

# -- 5) O2QueueWorker and O2RenderServer: interactive Scheduled Tasks ----
# These two can launch a real Chrome/Puppeteer browser (O2RenderServer
# always; O2QueueWorker whenever it falls back to Browsershot). Windows
# Services run in Session 0 - an isolated session with no real desktop -
# and Chrome can silently produce corrupt/truncated screenshots there, no
# matter which user account the service runs as. Confirmed by reproducing
# the exact same content directly (not as a service) with a correct result.
# A Scheduled Task triggered "at log on" runs in a real interactive
# session instead, where Chrome renders correctly.
Write-Step "Registering O2QueueWorker and O2RenderServer as interactive Scheduled Tasks..."

$taskUser = if ($ServiceUsername -ne "") {
    if ($ServiceUsername -like "*\*") { $ServiceUsername } else { "$env:COMPUTERNAME\$ServiceUsername" }
} else {
    "$env:USERDOMAIN\$env:USERNAME"
}

function Stop-O2OrphanProcesses {
    param([string]$InstallDir)

    # A Scheduled Task action here is wscript.exe -> cmd.exe -> php.exe or
    # node.exe. Ending/unregistering the task (or Stop-Process on php/node
    # by name) only ever touches the top or bottom of that chain - Windows
    # does NOT cascade-terminate the cmd.exe in between. Left running, that
    # orphaned cmd.exe just keeps looping (":loop ... goto loop" in
    # start-queue-worker.bat / start-render-server.bat) and silently spawns
    # its own worker again a few seconds later, right next to whatever this
    # script registers afterwards. Confirmed on a real station: this is what
    # caused 3 concurrent "queue:work" processes fighting over the same jobs
    # table, even after every task was freshly re-registered. taskkill /T
    # does a real process-tree kill, so use that instead of Stop-Process
    # before ever touching these tasks.
    $pattern = [regex]::Escape($InstallDir)
    Get-CimInstance Win32_Process -Filter "Name='wscript.exe' or Name='cmd.exe'" -ErrorAction SilentlyContinue |
        Where-Object { $_.CommandLine -and $_.CommandLine -match $pattern } |
        ForEach-Object {
            & taskkill.exe /F /T /PID $_.ProcessId 2>&1 | Out-Null
        }
}

function Install-O2InteractiveTask {
    param(
        [string]$Name,
        [string]$ScriptPath
    )

    if (-not (Test-Path $ScriptPath)) {
        throw "${Name}: script not found at $ScriptPath"
    }

    # Launch through run-hidden.vbs so no console window ever appears for a
    # cashier to accidentally close (which would kill the .bat's own
    # auto-restart loop along with it). If the underlying php.exe/node.exe
    # gets killed some other way, the still-running hidden loop restarts it
    # automatically same as before - nothing about the resiliency changes,
    # it's just invisible now.
    $vbsPath = Join-Path $InstallDir "run-hidden.vbs"
    if (-not (Test-Path $vbsPath)) {
        throw "run-hidden.vbs not found at $vbsPath - it must be bundled alongside the app"
    }

    Stop-O2OrphanProcesses -InstallDir $InstallDir
    Unregister-ScheduledTask -TaskName $Name -Confirm:$false -ErrorAction SilentlyContinue

    $action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$vbsPath`" `"$ScriptPath`"" -WorkingDirectory $InstallDir
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $taskUser
    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -ExecutionTimeLimit ([TimeSpan]::Zero) `
        -RestartCount 999 `
        -RestartInterval (New-TimeSpan -Minutes 1)
    $principal = New-ScheduledTaskPrincipal -UserId $taskUser -LogonType Interactive -RunLevel Highest

    Register-ScheduledTask -TaskName $Name -Action $action -Trigger $trigger `
        -Settings $settings -Principal $principal | Out-Null

    Start-ScheduledTask -TaskName $Name

    Write-Ok "$Name registered as a logon Scheduled Task and started"
}

Install-O2InteractiveTask -Name "O2QueueWorker" -ScriptPath (Join-Path $InstallDir "start-queue-worker.bat")
Install-O2InteractiveTask -Name "O2RenderServer" -ScriptPath (Join-Path $InstallDir "start-render-server.bat")

Write-Host ""
Write-Step "Verifying the installed code isn't a stale bundle..."
# Catches exactly the class of bug that took hours to diagnose on POS-012 on
# 2026-09-06: the installer's bundle/app folder wasn't refreshed after a
# backend printing fix, so the station silently kept running old code (one
# file at a time turned out to be stale - run-hidden.vbs, start-queue-worker.bat,
# PrintInvoiceJob.php, OrderPrintingService.php, render-server.js,
# ReceiptImageBuilder.php). Run this same check any time against an existing
# station: installer\verify-station.ps1 -InstallDir "<path>".
$verifyScript = Join-Path $PSScriptRoot "verify-station.ps1"
if (Test-Path $verifyScript) {
    & $verifyScript -InstallDir $InstallDir
} else {
    Write-Warn2 "verify-station.ps1 not found next to provision.ps1 - skipping the stale-bundle check."
}

Write-Host ""
Write-Host "Done! Cashier station fully set up:" -ForegroundColor Green
Write-Host "  - O2PrintBridge: Windows Service (services.msc)" -ForegroundColor Green
Write-Host "  - O2QueueWorker, O2RenderServer: Scheduled Tasks that start at logon" -ForegroundColor Green
Write-Host "    (Task Scheduler) - this is deliberate, not a Windows Service, so" -ForegroundColor Green
Write-Host "    Chrome renders correctly (see comment above for why)." -ForegroundColor Green
Write-Host ""
Write-Host "IMPORTANT: O2QueueWorker and O2RenderServer only start once someone" -ForegroundColor Yellow
Write-Host "logs in interactively as $taskUser. If this machine reboots with" -ForegroundColor Yellow
Write-Host "nobody logging in, printing stays down until someone logs in. Set up" -ForegroundColor Yellow
Write-Host "Windows auto-logon for that account if unattended reboots are a concern." -ForegroundColor Yellow
